### PR TITLE
Update MSRV: 1.56.1 -> 1.59.0

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Why does CI not run here?

**Comment by matthiasbeyer** [comment]
Hm. I fail to see why the CI workflow (`msrv.yml`) does not run.

Does someone else?

**Comment by DavidSouther** [comment]
It looks like it ran? https://github.com/mehcode/config-rs/actions/runs/3383804909

**Comment by matthiasbeyer** [comment]
No, that's just the fixup check, not the CI pipeline.

**Pull request merged**
