### PR TITLE
Add test with rust_decimal

### PR DESCRIPTION
**Pull request by matthiasbeyer**
To test issue #414

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Why the hell does it not find `rust_decimal`? Locally this works perfectly nice and `rust_decimal` is in `1.27.0`? :eyes:

**Comment by matthiasbeyer** [comment]
Issue was on users side, not gonna merge this to not unnecessarily bloat the dev-dependencies of the project.

**Comment by telcy** [comment]
According to rust_decimal docs: "The current minimum compiler version is 1.60.0 which was released on 2022-04-07."

That's why compiling for 1.59.0 failed.

**Comment by matthiasbeyer** [comment]
But wouldn't cargo still find the crate and try to compile it and then fail? From what I see, it fails to actually find the version!

**Comment by telcy** [comment]
I installed locally 1.59.0 and it failed with same output.

Probably just an early exit because of the rust version defined for the crate?
https://github.com/paupino/rust-decimal/blob/bc8b53a7ca697945642ebe3a44f38d9cd6f0bd83/Cargo.toml#L19

https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field

**Comment by matthiasbeyer** [comment]
Hm, okay. I didn't know cargo can do that. Thanks for investigating this!

**Pull request closed without merging**
