### PR TITLE
Fix nested arrays (by reworking array handling) - backport

### LINKED ISSUE #464: Nested arrays badly mangled
To reproduce:
```
    #[test]
    fn list() {
        let jtxt = r#" { "proxy_ports": [ [1,2] ] } "#;
        let jval: serde_json::Value = serde_json::from_str(jtxt).unwrap();
        //dbg!(&jval);
        let jcfg = config::Config::try_from(&jval).unwrap();
        //dbg!(&jcfg);
        let jret: serde_json::Value = jcfg.clone().try_deserialize().unwrap();
        println!("json roundtrip: {jret:#?}");

        let ttxt = r#" proxy_ports = [ [1,2] ] "#;
        let tval: toml::Value = toml::from_str(ttxt).unwrap();
        //dbg!(&tval);
        let tcfg = config::Config::try_from(&tval).unwrap();
        //dbg!(&tcfg);
        let tret: Result<String, _> = tcfg.clone().try_deserialize()
            .map(|v: toml::Value| toml::to_string(&v).unwrap());
        println!("toml roundtrip: {tret:#?}");
    }
```

Expected output:
```
json roundtrip: Object {
    "proxy_ports": Array [
        Array [
            Number(1),
            Number(2),
        ],
    ],
}
toml roundtrip: Ok(
    "proxy_ports = [[1, 2]]\n"
)
```

Actual output:

```
json roundtrip: Object {
    "proxy_ports": Array [
        Null,
        Number(1),
        Number(2),
    ],
}
toml roundtrip: Err(
    invalid type: unit value, expected any valid TOML value,
)
```

Uncommenting the dbgs in the repro above shows this, which seems entirely wrong:

```
[crates/arti/src/onion_proxy.rs:143] &jcfg = Config {
    defaults: {},
    overrides: {
        Subscript(
            Identifier(
                "proxy_ports",
            ),
            1,
        ): Value {
            origin: None,
            kind: I64(
                1,
            ),
        },
        Subscript(
            Identifier(
                "proxy_ports",
            ),
            2,
        ): Value {
            origin: None,
            kind: I64(
                2,
            ),
        },
    },
    sources: [],
    cache: Value {
        origin: None,
        kind: Table(
            {
                "proxy_ports": Value {
                    origin: None,
                    kind: Array(
                        [
                            Value {
                                origin: None,
                                kind: Nil,
                            },
                            Value {
                                origin: None,
                                kind: I64(
                                    1,
                                ),
                            },
                            Value {
                                origin: None,
                                kind: I64(
                                    2,
                                ),
                            },
                        ],
                    ),
                },
            },
        ),
    },
}
```

### PR DESCRIPTION
**Pull request by ijackson**
Backport of #465 to 0.13.x branch.  Fixes #464 there.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Please re-do the commits with the `-x` flag on `git-cherry-pick` (as [noted here](https://github.com/mehcode/config-rs/pull/465#issuecomment-1775572892)) so that the backported commits refer to the original ones.

**Comment by ijackson** [comment]
> Please re-do the commits with the `-x` flag on `git-cherry-pick` (as [noted here](https://github.com/mehcode/config-rs/pull/465#issuecomment-1775572892)) so that the backported commits refer to the original ones.

Ah sorry, didn't see that comment.  FTR, I did:  `for f in `git-rev-list --reverse --topo-order nested-array~4..nested-array`; do echo git cherry-pick -x $f; done | sh -xe`

**Comment by matthiasbeyer** [comment]
> ```
> for f in `git-rev-list --reverse --topo-order nested-array~4..nested-array`; do echo git cherry-pick -x $f; done | sh -xe
> ```

The following would have been sufficient:

```
git cherry-pick -sx $(git merge-base master^1 master^2)..master^2
```

<details>
<summary>Explanation of the above command</summary>
Explanation: The above means cherry-pick the changes:

* from the merge base of the commit to the left of current master and the commit to the right of current master (the last commit of the previously merged PR)
* to the commit to the right of current master (the last commit of the previously merged PR)

You can replace the `git cherry-pick -sx` with `git log --oneline` and you'll see that this is exactly the range you want to pick.
</details>

But no worries! Log looks good now, let's see what CI tells us!

---

It seems that we have to bump the MSRV for the next 0.13.x release ... I don't like that but I don't see a better way, tbh.
I think I'll do that and rebase this PR then. No need to worry for you!

**Comment by ijackson** [comment]
I think we could fix this on the 0.13 branch by committing a suitable `Cargo.lock`.  Would you like me to do that?

**Comment by ijackson** [comment]
> It seems that we have to bump the MSRV for the next 0.13.x release ... I don't like that but I don't see a better way, tbh. I think I'll do that and rebase this PR then. No need to worry for you!

Please let me have a go at fixing it with a `Cargo.lock` instead?  I will try that tomorrow; it's getting rather late for me here now.

**Comment by matthiasbeyer** [comment]
> Please let me have a go at fixing it with a `Cargo.lock` instead? I will try that tomorrow; it's getting rather late for me here now.

Yes, feel free to try. Although I am not sure about whether that would help, as downstream might still run into the issue that they have a new `log` crate version (for example) but an compiler too old for that crate version.

But I see where you're going. I'll stop my efforts for the MSRV update on the release branch (#487) now!

**Comment by ijackson** [comment]
I have succeeded, by providing a `Cargo.lock`.  I will tidy up my branch and make an MR of it.

**Comment by ijackson** [comment]
I've rebased this to pick up the CI fix from #496

**Comment by matthiasbeyer** [comment]
I am on vacation until late tomorrow. I hope I can get back to this as soon as possible.

**Review by matthiasbeyer — APPROVED** [review]
As all commits were picked from approved PRs, I don't see why I shouldn't approve this as well :laughing:

**Pull request merged**
