### PR TITLE
Adds File::with_name which automatically detects file format

### PR DESCRIPTION
**Pull request by JordiPolo**
My humble attempt at implementing #21, I'm new at using Rust so there may be dragons.

TODO:
- [ ] Tests. Should I add tests? Where? I only saw them in the config.rs file.
- [ ] Docs. Also, where should I add the documentation?

### CODE REVIEW

**Comment by mehcode** [comment]
@JordiPolo This looks great. Thanks for starting this. 

I'm currently in the middle of a large internal refactor to support a number of the issues on here. I'll make sure this gets merged in when I finish.

**Comment by JordiPolo** [comment]
Don't hesitate closing this. I can redo this later on the new code

**Comment by mehcode** [comment]
@JordiPolo If you're still able to pick this back up, I'd appreciate it.

**Comment by mehcode** [comment]
@JordiPolo Nevermind. I decided to just update your PR. Thanks for starting this then.

**Comment by JordiPolo** [comment]
Thanks, sorry for dropping this

**Pull request merged**
