### PR TITLE
Refactor/pedantic lints

### PR DESCRIPTION
**Pull request by danieleades**
address a number of 'pedantic' lints

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]
Thank you for all your contributions, they are highly appreciated! :heart:

**Comment by danieleades** [comment]
@matthiasbeyer do you want me to add compiler flags to make sure these *stay* fixed, or do you prefer to make these fixes a one-off?

**Comment by matthiasbeyer** [comment]
What do you mean with "Compiler flags"? You mean clippy, right?

**Comment by danieleades** [comment]
> What do you mean with "Compiler flags"? You mean clippy, right?

yeah, exactly. There's a few lints I used for these PRs, but which do not currently generate any warnings or errors unless specifically requested on the command line

**Comment by matthiasbeyer** [comment]
Yes please, I think that's a good idea!

**Comment by danieleades** [comment]
> Yes please, I think that's a good idea!

most of the ones in this PR are a little pedantic...
I'll have a think about what might be appropriate, and stick them in a separate PR for review

**Review by matthiasbeyer — APPROVED** [review]

**Pull request merged**
