### PR TITLE
Make the parse list key to lowercase when insert the keys

### PR DESCRIPTION
**Pull request by bigduu**
#428

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Hi,
sorry for the slow response, I was on vacation.

The patch itself looks good. But I am slowly getting the impression that the whole env-parsing implementation was a mistake. It gets more and more complex.

Still, I give this a go for now.

**Comment by matthiasbeyer** [comment]
Care to make CI green here? :smiley:

**Comment by bigduu** [comment]
sorry，late reply，will let the CI green later: )

**Comment by bigduu** [comment]
The commit check detail is overdue, could you please approve the workflows?

**Comment by matthiasbeyer** [comment]
Done.
The signoff is missing. Please rebase and signoff your commit (and remove the merge commit).

**Comment by bigduu** [comment]
Thanks, done

**Comment by bigduu** [comment]
do we have any updates? Please help to merge the PR, thanks

**Comment by matthiasbeyer** [comment]
Thanks for reminding me!

**Comment by bigduu** [comment]
Np,Thanks 😄

**Pull request merged**
