### PR TITLE
Update to rust 2018 edition

### PR DESCRIPTION
**Pull request by kpcyrd**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Hi,

awesome that you tackle this! These are unrelated changes tho, would you please file two PRs for this (splitting the port to nom 6 off to a new PR)?

**Comment by kpcyrd** [comment]
I've removed the nom6 commit from the branch

**Comment by matthiasbeyer** [comment]
Looks good, lets see what CI tells us! :partying_face:

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Okay, this looks really good.

I saw that you update dependencies in the same commit. Could you split that off to individual commits? So

1. Updating to Rust 2018
2. Updating the "glob" dependency in the examples
3. Updating "lazy_static"

Besides that this looks great and is IMO ready for merging.

**Review by matthiasbeyer — APPROVED** [review]
Okay, waiting for CI before merge.

Thank you very much for your contribution! :tada:

**Pull request merged**
