### PR TITLE
Adjust environment variable handling

### LINKED ISSUE #47: Picking up values from environment not working
Hi,

I am trying to use the environment only, to grep the configuration. Because that did not work, I also tried with an additional Settings.toml. Then the value from file is picked up, but not the environment.

Code:

    let mut settings = config::Config::default();
    settings
       .merge(config::File::with_name("Settings"))
        .unwrap()
        .merge(config::Environment::with_prefix("APP"))
        .unwrap();

    let x = settings.get::<String>("foo").expect("ok");
    println!("CFG: {:?}", x);

Settings.toml:
`foo = "20"`

Calling the program with `APP_FOO=10 target/debug/prog`. Only the value from toml is picked up.

I must be doing something very stupid, but I cannot get this to work. Can you spot my error?

**UPDATE** Also tried the simple example, with APP_DEBUG=FOO without success. The toml file wins.

The crazy thing is that to me the code in Environment looks fine, I am just not getting what is going on.

**UPDATE**
See new comment https://github.com/mehcode/config-rs/issues/47#issuecomment-339638438 below.

### PR DESCRIPTION
**Pull request by ChriFo**
One more try to resolve #47

### CODE REVIEW

**Comment by mehcode** [comment]
Looks great! Only change I'd suggest is to make is to force a `_` after the env key prefix. What do you think? A similar library in Go, [viper](https://github.com/spf13/viper), does this.

**Comment by theherk** [comment]
I know this is closed, but on the topic, the in-code samples suggest `with_prefix("APP")` but what actually works is `with_prefix("app")`. I'm happy to contribute to resolving this, but I'm unclear on the intended behavior. Should prefix be written as upper or lower, and based on code, should the environment be upper or lower. Then based on the env variable being upper or lower, should the value set be upper or lower.

I'm thinking the most simple magic here is to upper whatever is put into `with_prefix` so that "app", "aPp", and "APP" are all "APP_" in the environment, then lower everything once parsed so `app_kEy`, `aPP_key`, and `APP_KEY` are all represented by the symbol `key` in code.

**Comment by ChriFo** [comment]
@theherk I added a test to demonstrate the behavior of this PR. As you can see lower, upper and even mixed cases for both - prefix and environment variables - are suitable!

**Comment by mehcode** [comment]
This is great @ChriFo. Thanks for the contribution.

**Pull request merged**
