### PR TITLE
Add documentation to File `required` setter.

### PR DESCRIPTION
**Pull request by DavidSouther**

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
The CI error comes from a too old rustc version on our side. #389 should fix that. I'll ask you to rebase as soon as #389 has landed, or if you don't care too much, I can do the rebase for you!

**Comment by matthiasbeyer** [comment]
Okay, please rebase :tada:

**Comment by DavidSouther** [comment]
Looks like Github did a merge when I synced - is that OK, or do you need it to be a rebase?

**Comment by matthiasbeyer** [comment]
Please do a rebase. What github does here messes up the history and just produces noise in the repository, so I'd love to see a rebase here if you don't mind!

**Comment by matthiasbeyer** [comment]
Thank you very much! I'll merge as soon as CI is green.

**Pull request merged**
