### PR TITLE
rename try_into to try_deserialize to avoid confusion

### PR DESCRIPTION
**Pull request by conradludgate**
For #162

### CODE REVIEW

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Diff looks good!
Please squash the commits into one and use an appropriate commit message!

**Comment by matthiasbeyer** [comment]
Yeah, please remove the `feat:` prefix from the commit message, then I'll merge!

**Comment by conradludgate** [comment]
Bah, I'm a sucker for conventional commits. I'll change it up though

**Review by matthiasbeyer — APPROVED** [review]
I don't think conventional commits provide any value,... we can discuss this if you want, but here's not the place! :smile: :heart:

**Pull request merged**
