### PR TITLE
small refactors of 'msrv' workflow

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Can you please split the commit into several so that we have one commit per type of change?

**Comment by danieleades** [comment]
> Can you please split the commit into several so that we have one commit per type of change?

I feel like the changes in this PR are fairly atomic already. How do you see this being broken down?

**Comment by matthiasbeyer** [comment]
One change for the `minimal` key and one for the other change,... If they are too tightly related in your opinion, at least a commit message that explains what this change actually does would be really nice.

Either way, thanks for your contribution! :heart:

**Comment by danieleades** [comment]
> One change for the `minimal` key and one for the other change,... If they are too tightly related in your opinion, at least a commit message that explains what this change actually does would be really nice.
> 
> Either way, thanks for your contribution! heart

done. let me know if you're happy with those

**Review by matthiasbeyer — APPROVED** [review]

**Pull request merged**
