### PR TITLE
ensure clippy runs on all targets

### PR DESCRIPTION
**Pull request by danieleades**
note that there are clippy false positives due to https://github.com/rust-lang/rust-clippy/issues/8140

### CODE REVIEW

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Can you please split the commits so that we have only one commit per type of change?

**Review by matthiasbeyer — APPROVED** [review]

**Comment by danieleades** [comment]
note that there is some remaining use of deprecated code in the examples. It's not clear to me how these use cases should be supported using the builder API. I've *allowed* these for now, but they should be addressed in a future PR

**Comment by matthiasbeyer** [comment]
You're adding `#[must_use]` f7899fd in and removing it again in 48f49c6 - was this by accident? :laughing:

**Comment by danieleades** [comment]
> You're adding `#[must_use]` [f7899fd](https://github.com/mehcode/config-rs/commit/f7899fd2dbefb311357af9f00af17f4b47fcece4) in and removing it again in [48f49c6](https://github.com/mehcode/config-rs/commit/48f49c684a266b8ab1a2353de74bdcf6c9d1ccd0) - was this by accident? laughing

suspect that snuck in during a rebase. I'll take a look

**Comment by matthiasbeyer** [comment]
For the "global" example you can cherry-pick https://github.com/matthiasbeyer/config-rs/commit/1eff7b3a222aef41bff692377fc85fb1b00d760d to this PR if you want (or wait until the [actions](https://github.com/matthiasbeyer/config-rs/actions/runs/1633881795) succeed) :laughing:

**Comment by danieleades** [comment]
> For the "global" example you can cherry-pick [matthiasbeyer@1eff7b3](https://github.com/matthiasbeyer/config-rs/commit/1eff7b3a222aef41bff692377fc85fb1b00d760d) to this PR if you want (or wait until the [actions](https://github.com/matthiasbeyer/config-rs/actions/runs/1633881795) succeed) laughing

this change doesn't look equivalent to the original to me. If i'm reading it right, the original example is *mutable* global config, while the updated version is *immutable* global config.

in any case, I think I'd rather leave it out of this PR. Don't want to over-complicate the review!

**Comment by matthiasbeyer** [comment]
Okay!

**Comment by matthiasbeyer** [comment]
Do you consider this review/merge ready? :smile:  I think I lost track a bit!

**Comment by danieleades** [comment]
> Do you consider this review/merge ready? smile I think I lost track a bit!

yes, i'm not planning to do any more on this PR

**Review by matthiasbeyer — APPROVED** [review]

**Pull request merged**
